### ISSUE TITLE
Can't view in Rviz: "No tf data.  Actual error: Fixed Frame [map] does not exist"

### ISSUE THREAD

**Issue by terencenwz** [RGring/drl_local_planner_ros_stable_baselines#29]
Hi, I got this error after running: roslaunch rl_bringup setup.launch ns:="sim1" rl_params:="rl_params_scan"

Does anyone knows how to resolve this?

![image](https://user-images.githubusercontent.com/17173535/152691112-e3d96254-235e-497c-bdaa-4ae8fc8f75cc.png)

**Comment by terencenwz** [comment]
Solved. 
I ran 
rviz -d robot_navigation.rviz
instead of 
roslaunch rl_bringup rviz.launch ns:="sim1" 
which caused the error. 

The launch file is required to map the topics to the new namespace

**Comment by yani-rl-ai** [comment]
Hey @terencenwz which ROS version do you use?

**Comment by terencenwz** [comment]
The same version as in the docker file. Kinetic.
