### ISSUE TITLE
Cant find LUA_INCLUDE_DIR

### ISSUE THREAD

**Issue by parhartanvir** [RGring/drl_local_planner_ros_stable_baselines#3]
Hi, thanks for open-sourcing the project. 

I get the following error while  making the project.
`CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LUA_INCLUDE_DIR [(ADVANCED)]`

Does the project require Lua?

Thanks,
Tanvir

**Comment by RGring** [comment]
No that I know. How did you build the project?
