### ISSUE TITLE
Issue loading pre-trained models

### ISSUE THREAD

**Issue by danieldugas** [RGring/drl_local_planner_ros_stable_baselines#9]
Hi,

I've been trying to load the PPO2 models 

```PPO2.load("example_agents/ppo2_1_raw_data_cont_0/ppo2_1_raw_data_cont_0.pkl")```

And get the following error: ```ValueError: Cannot feed value of shape (1344, 256) for Tensor 'Placeholder_4:0', which has shape '(1600, 256)'```

I did some digging, one one hand the weights saved in your pickle file are for a fc1 layer of size 1344, 256. On the other hand, the conv1d operations defined in your custom stable-baselines fork lead to a fc1 layer of size 1600, 256.

In order for the weights to be the correct size (1344, 256), the output of the second conv1d should be of size (?, 21, 64), but instead we obtain (?, 25, 64).

In [common_custom_policies.py](https://github.com/RGring/drl_local_planner_ros_stable_baselines/blob/master/rl_agent/src/rl_agent/common_custom_policies.py)
```
def laser_cnn_multi_input(state, **kwargs):
    """
    1D Conv Network

    :param state: (TensorFlow Tensor) state input placeholder
    :param kwargs: (dict) Extra keywords parameters for the convolutional layers of the CNN
    :return: (TensorFlow Tensor) The CNN output layer
    """
    # scan = tf.squeeze(state[:, : , 0:kwargs['laser_scan_len'] , :], axis=1)
    scan = tf.squeeze(state[:, : , 0:kwargs['laser_scan_len'] , :], axis=1)
    wps = tf.squeeze(state[:, :, kwargs['laser_scan_len']:, -1], axis=1)
    # goal = tf.math.multiply(goal, 6)

    kwargs_conv = {}
    activ = tf.nn.relu
    layer_1 = activ(conv1d(scan, 'c1d_1', n_filters=32, filter_size=5, stride=2, init_scale=np.sqrt(2), **kwargs_conv))
    layer_2 = activ(conv1d(layer_1, 'c1d_2', n_filters=64, filter_size=3, stride=2, init_scale=np.sqrt(2), **kwargs_conv))
    layer_2f = conv_to_fc(layer_2)
```

where conv1d is defined [here](https://github.com/hill-a/stable-baselines/compare/master...RGring:added_1d_conv_layer)

I've been making sure to use tensorflow 1.13.1.

Could it be that you used a different version of the conv1d code during training?

**Comment by RGring** [comment]
Hi. I will have a look... Just wondering, if the same problem also occurs on the discrete agent?

**Comment by danieldugas** [comment]
I'm seeing the same problem with the discrete agent, yes.

**Comment by RGring** [comment]
Hi. I can reproduce your error. It happens to me, when I do not launch the simulation (step 4 in "Run pretrained Agents" --> "Run agent trained on raw data, discrete action space, stack size 1"). Can you check, if you have started the simulation? Unfortunately, it is not possible to have all in one launch-file, because the DRL-component runs with python3 and ROS runs with python2.

Though, I don't see yet the connection between the error message and the missing simulation, but it solved it for me :).

Looking forward to your feedback

**Comment by RGring** [comment]
I also added some examples to run the pre-trained agents in docker in case you want to try that.

**Comment by danieldugas** [comment]
After looking inside the docker build, I was able to pinpoint the right value for the rosparam, and to get the pretrained models to load with the non-forked stable-baselines, and without ROS. 

[see here](https://github.com/RGring/drl_local_planner_ros_stable_baselines/compare/master...danieldugas:master)

If you're interested I can make a PR. In any case, thanks for your help!

**Comment by RGring** [comment]
Hi Daniel,
Thanks for your feedback and the improvements. You are very welcome to make a PR!
